# This workflow builds the full project through Maven.
# The webapp is built via the Maven plugin, using an embedded Node.js.
name: Build Dicoogle 2

on:
  push:
    branches: [ release/2.X, releases/2.5.X ]
  pull_request:
    branches: [ release/2.X, releases/2.5.X ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: ['8']

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: ${{ matrix.java-version }}
    - name: Build with Maven
      run: mvn -B package --file pom.xml
